[project]
name = "speech-recognition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "scipy>=1.16.2",
    "sounddevice>=0.5.2",
    "torch>=2.9.0",
    "transformers>=4.57.1",
    "numpy==1.24"
]
